from github import Github
import hmac
import hashlib
import os
from dotenv import load_dotenv

load_dotenv()

class GitHubHandler:
    
    def __init__(self):
        self.github = Github(os.getenv("GITHUB_TOKEN"))
        self.webhook_secret = os.getenv("GITHUB_WEBHOOK_SECRET")
        print("✅ GitHub connected!")
    
    def verify_webhook(self, payload: bytes, signature: str):
        """
        Verifies request actually came from GitHub
        """
        expected_signature = hmac.new(
            self.webhook_secret.encode(),
            payload,
            hashlib.sha256
        ).hexdigest()
        
        return hmac.compare_digest(
            f"sha256={expected_signature}",
            signature
        )
    
    def get_pr_files(self, repo_name: str, pr_number: int):
        """
        Gets all changed files in a Pull Request
        """
        print(f"📥 Getting files from PR #{pr_number} in {repo_name}")
        
        repo = self.github.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        
        files = []
        for file in pr.get_files():
            if file.patch:
                files.append({
                    "filename": file.filename,
                    "content": file.patch,
                    "additions": file.additions,
                    "deletions": file.deletions
                })
                print(f"  📄 Found: {file.filename}")
        
        return files
    
    def post_comment(self, repo_name: str, pr_number: int, review_result: dict):
        """
        Posts AI review as a comment on GitHub PR
        """
        repo = self.github.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        
        comment = self.format_comment(review_result)
        pr.create_issue_comment(comment)
        print(f"✅ Review comment posted to PR #{pr_number}!")
    
    def format_comment(self, review: dict):
        """
        Formats review results as markdown comment
        """
        score = review["overall_score"]
        
        if score >= 7:
            status_emoji = "✅ Good code!"
        elif score >= 5:
            status_emoji = "⚠️ Needs some fixes"
        else:
            status_emoji = "❌ Major issues found"
        
        comment = f"""
## 🤖 AI Code Review — Score: {score}/10 {status_emoji}

---

### 🐛 Bugs Found: {len(review['bugs']['bugs'])}
"""
        if review['bugs']['bugs']:
            for bug in review['bugs']['bugs']:
                comment += f"""
> **Line {bug['line']}** — Severity: `{bug['severity'].upper()}`
>
> 🔴 **Problem:** {bug['description']}
>
> 💡 **Fix:** {bug['fix']}

---
"""
        else:
            comment += "\n> ✅ No bugs found!\n"
        
        comment += f"""
### 🔒 Security Issues: {len(review['security']['vulnerabilities'])}
"""
        if review['security']['vulnerabilities']:
            for vuln in review['security']['vulnerabilities']:
                comment += f"""
> **{vuln['type']}** — Line {vuln['line']} — `{vuln['severity'].upper()}`
>
> 🔴 **Risk:** {vuln['description']}
>
> 💡 **Fix:** {vuln['fix']}

---
"""
        else:
            comment += "\n> ✅ No security issues found!\n"
        
        comment += "\n*Review generated by AI Code Reviewer 🤖*"
        
        return comment